### ISSUE TITLE
showing Incorrect Missing data in HTML Report

### ISSUE THREAD

**Issue by harika1419** [julioasotodv/spark-df-profiling#25]
After generating the HTML report using spark-df- profiling It is showing the percentage of Missing data as 0%.

Even though dataframe has some missing data

**Comment by adutchengineer** [comment]
Could you give an example?

**Comment by shhanani** [comment]
Is this fixed yet? mine also shows wrong missing data as 0%

**Comment by shhanani** [comment]
@harika1419 I think I found the issue. It's in line 397. 
Change to this:
```
results_data = df.select(column).na.drop().agg(countDistinct(col(column)).alias("distinct_count"),
                                                       count(col(column)).alias("count")).toPandas()
```
@julioasotodv you might need to look at this solution

**Comment by shhanani** [comment]
@julioasotodv you might need to look at this solution

**Comment by harika1419** [comment]
Hi...
That issue was fixed after upgrading the spark from 1.6 to 2.3.3

**Comment by shhanani** [comment]
Hi @harika1419,
Thanks for informing. I'm facing this issue while using spark 2.4.2, that is why I thought its not fixed yet.

**Comment by Strauman** [comment]
I'm on Spark 3.1.0, and it's showing wrong. Also the number of zeros are wrong.
